(function() {var implementors = {};
implementors["sgx_tcrypto"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tcrypto/struct.SgxShaHandle.html\" title=\"struct sgx_tcrypto::SgxShaHandle\">SgxShaHandle</a>",synthetic:false,types:["sgx_tcrypto::crypto::SgxShaHandle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tcrypto/struct.SgxSha1Handle.html\" title=\"struct sgx_tcrypto::SgxSha1Handle\">SgxSha1Handle</a>",synthetic:false,types:["sgx_tcrypto::crypto::SgxSha1Handle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tcrypto/struct.SgxCmacHandle.html\" title=\"struct sgx_tcrypto::SgxCmacHandle\">SgxCmacHandle</a>",synthetic:false,types:["sgx_tcrypto::crypto::SgxCmacHandle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tcrypto/struct.SgxHmacHandle.html\" title=\"struct sgx_tcrypto::SgxHmacHandle\">SgxHmacHandle</a>",synthetic:false,types:["sgx_tcrypto::crypto::SgxHmacHandle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tcrypto/struct.SgxEccHandle.html\" title=\"struct sgx_tcrypto::SgxEccHandle\">SgxEccHandle</a>",synthetic:false,types:["sgx_tcrypto::crypto::SgxEccHandle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tcrypto/struct.SgxRsaPrivKey.html\" title=\"struct sgx_tcrypto::SgxRsaPrivKey\">SgxRsaPrivKey</a>",synthetic:false,types:["sgx_tcrypto::crypto::SgxRsaPrivKey"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tcrypto/struct.SgxRsaPubKey.html\" title=\"struct sgx_tcrypto::SgxRsaPubKey\">SgxRsaPubKey</a>",synthetic:false,types:["sgx_tcrypto::crypto::SgxRsaPubKey"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tcrypto/struct.SgxAesHandle.html\" title=\"struct sgx_tcrypto::SgxAesHandle\">SgxAesHandle</a>",synthetic:false,types:["sgx_tcrypto::crypto::SgxAesHandle"]},];
implementors["sgx_tprotected_fs"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tprotected_fs/struct.SgxFileStream.html\" title=\"struct sgx_tprotected_fs::SgxFileStream\">SgxFileStream</a>",synthetic:false,types:["sgx_tprotected_fs::fs::SgxFileStream"]},];
implementors["sgx_trts"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_trts/c_str/struct.CString.html\" title=\"struct sgx_trts::c_str::CString\">CString</a>",synthetic:false,types:["sgx_trts::c_str::CString"]},];
implementors["sgx_tse"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sgx_tse/alignbox/struct.AlignBox.html\" title=\"struct sgx_tse::alignbox::AlignBox\">AlignBox</a>&lt;T&gt;",synthetic:false,types:["sgx_tse::alignbox::AlignBox"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()