[package]
name = "try-lock"
version = "0.2.2" # remember to update html_root_url
description = "A lightweight atomic lock."
keywords = ["lock", "atomic"]
categories = ["concurrency"]
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT"
repository = "https://github.com/seanmonstar/try-lock"
homepage = "https://github.com/seanmonstar/try-lock"
documentation = "https://docs.rs/try-lock"
readme = "README.md"
[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
enclave_unit_test = ["sgx_tunittest"]

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
sgx_tunittest = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }